### ISSUE TITLE
Add CustomImageButton reusable component

### ISSUE THREAD

**Issue by imasharc** [imasharc/RAMDHD#1]
### Problem
Add button with image and text. Neither Button or ImageButton component allow for adding both image and label and customizing the style. Custom Image Button component needs to be made.

### Solution
Make reusable CustomImageButton component and put it in the Main window.

### To-Do

- [ ] Add Image binding
- [ ] Add text label binding
- [ ] Respond to Gesture call
- [ ] Execute binded function on Gesture call

**Comment by imasharc** [comment]
- [x]  Add Image binding
- [x]  Add text label binding
- [x]  Respond to Gesture call
- [x]  Execute binded function on Gesture call

All done in commits:
- 23e9a1e
- 633d46f
- 957753c
