### ISSUE TITLE
Refactor Timer screen

### ISSUE THREAD

**Issue by imasharc** [imasharc/RAMDHD#4]
### Problem
Timer screen currently looks out-of-style and its appearance is primitive

### Solution
CorrectTimer screen style and appearance to be welcoming and pleasing

### To-Do

- [ ] Add "digital clock" appearance
- [ ] Unify the color palette

**Comment by imasharc** [comment]
As mentioned in the following commits:

- [1998105 - refactor(TimerPage.xaml): Change Time picker to click-and-scroll](https://github.com/imasharc/RAMDHD/commit/1998105e7dfbd31b9c052bd118a788dfd69da4b3)
- [d9676df - refactor(TimerPage.xaml.cs): Add functionality for click-and-scroll timer](https://github.com/imasharc/RAMDHD/commit/d9676df03abf84c4c046198114f7859c2fc304a3)

The following problems have been solved:

- [x] Add simplified "digital clock" appearance
- [x] Add better-looking style
- [x] Improve/Refactor timer functionality
    - [x] Click-and-scroll time adjust
    - [x] Start/Stop/Reset buttons functionality

The functionality may still be improved but that goes for another issue
